"""add bakong payment provider

Revision ID: 0c685dd1b057
Revises: f7dd45156a44
Create Date: 2026-07-10 16:40:02.906578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c685dd1b057'
down_revision = 'f7dd45156a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=mysql.ENUM('payway', 'mock'),
               type_=sa.Enum('payway', 'bakong', 'mock'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.Enum('payway', 'bakong', 'mock'),
               type_=mysql.ENUM('payway', 'mock'),
               existing_nullable=False)

    # ### end Alembic commands ###
