"""add wallet tables and wallet_amount

Revision ID: 8a4465037265
Revises: e7f8a9b0c1d2
Create Date: 2026-07-11 15:04:54.820996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a4465037265'
down_revision = 'e7f8a9b0c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('wallet_topups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.Enum('bakong', 'mock'), nullable=False),
    sa.Column('qr_md5', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'cancelled', 'expired'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('topup', 'purchase', 'refund', 'admin_credit', 'admin_debit'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=mysql.ENUM('payway', 'bakong', 'mock'),
               type_=sa.Enum('payway', 'bakong', 'mock', 'wallet'),
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=mysql.ENUM('khqr', 'card', 'abapay'),
               type_=sa.Enum('khqr', 'card', 'abapay', 'wallet'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('method',
               existing_type=sa.Enum('khqr', 'card', 'abapay', 'wallet'),
               type_=mysql.ENUM('khqr', 'card', 'abapay'),
               existing_nullable=False)
        batch_op.alter_column('provider',
               existing_type=sa.Enum('payway', 'bakong', 'mock', 'wallet'),
               type_=mysql.ENUM('payway', 'bakong', 'mock'),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('wallet_amount')

    op.drop_table('wallet_transactions')
    op.drop_table('wallet_topups')
    op.drop_table('wallets')
    # ### end Alembic commands ###
