"""add awaiting_stock order status

Revision ID: c7ed383edebf
Revises: 8a4465037265
Create Date: 2026-07-11 16:04:34.767488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7ed383edebf'
down_revision = '8a4465037265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending_payment', 'paid', 'fulfilled', 'cancelled', 'refunded', 'failed'),
               type_=sa.Enum('pending_payment', 'awaiting_stock', 'paid', 'fulfilled', 'cancelled', 'refunded', 'failed'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending_payment', 'awaiting_stock', 'paid', 'fulfilled', 'cancelled', 'refunded', 'failed'),
               type_=mysql.ENUM('pending_payment', 'paid', 'fulfilled', 'cancelled', 'refunded', 'failed'),
               existing_nullable=False)

    # ### end Alembic commands ###
